### ISSUE TITLE
M1 Support

### ISSUE THREAD

**Issue by sam1am** [wiremoons/csv2sql#4]
I get this error on M1 mac: 

rosetta error: overlapping Mach-O segments:
 ./csv2sql-macx64[1]    65753 abort      ./csv2sql-macx64 -f mycsv.csv -k=true -t

**Comment by wiremoons** [comment]
Hi @sam1am 

The error is due to running the Intel CPU compiled binary version on an Apple Silicon M1 CPU  system. The binary should run under *Rosetta* - but it is better to use a native M1 version if possible.

So, I have just added a new released version 1.2 that now includes a native Apple Silicon M1 binary version as well - so if you download that one instead and give it a try, it should run ok for you.

If you want to build you own copy - I have also now added the compile option to the *Makefile* under *arm64*.

Hope that helps.

Simon
